name: Stop Azure VM (Night)

on:
  workflow_dispatch:
  schedule: 
    - cron: '0 18 * * *'   # 18:00 UTC = 11:30 PM IST (India Standard Time)

jobs:
  stop-vm:
    runs-on: ubuntu-latest
    permissions:
      id-token:  write
      contents: read

    steps:
      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets. AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets. AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Stop VM
        run: |
          az vm deallocate \
            --resource-group Neeraj_azure_VM \
            --name myVm
