name: TEST â€“ Cron Start Azure VM (Every 5 min)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)

jobs:
  test-start-vm:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Debug trigger info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Run time (UTC):"
          date -u
          echo "Run time (IST):"
          TZ=Asia/Kolkata date

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Start VM (idempotent)
        run: |
          az vm start \
            --resource-group Neeraj_azure_VM \
            --name myVm
